export const Routes = {
    Onboarding: 'Onboarding',
    Presentation: 'Presentation',
    Login: 'Login',
    SignUp: 'SignUp',
    CompleteProfile: 'CompleteProfile',
    Home: 'Home',
    ForgetPassword: 'ForgetPassword',
    ConfirmPhone: 'ConfirmPhone',
    DeleteAccount: 'DeleteAccount',
    Security: 'Security',
    Settings: 'Settings',
    Memberships: 'Memberships',
    NotificationSettings: 'NotificationSettings',
    PrivacySettings: 'PrivacySettings',
    Profile: 'Profile',
    Game: 'Game',
    Forum: 'Forum',
    CreateNewPassword: 'CreateNewPassword'
}
