name: Deploy Frontend Apps

on:
  push:
    branches: [ "main" ]

env:
  REACT_APP_API_DOMAIN: ${{ REACT_APP_API_DOMAIN }}
  REACT_APP_AUTH_TOKEN_NAME: ${{ REACT_APP_AUTH_TOKEN_NAME }}
  REACT_APP_FB_ID: ${{ REACT_APP_FB_ID }}
  REACT_APP_GOOGLE_ID: ${{ REACT_APP_GOOGLE_ID }}
  REACT_APP_LOCATION: ${{ REACT_APP_LOCATION }}
  REACT_APP_AUTH_USER_INFO: ${{ REACT_APP_AUTH_USER_INFO }}

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: production
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
    - run: npm i --force

    - name: Build admin app
    - run: npm run build:admin --if-present

    - name: Build Users App
    - run: npm run build:app --if-present
    
    - uses: actions/checkout@v3
    - name: Deploy to server
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{ SSH_KEY }}
      with:
        flags: '-avzr --delete'
        options: '-progress -v'
        src: '/packages/admin/build'
        dest: "${{ SSH_USERNAME }}@${{ SSH_HOST }}:/var/www/html"

    - name: Display status from deploy
      run: echo "${{ steps.deploy.outputs.status }}"
