name: Deploy Frontend Apps

on:
  push:
    branches: [ "main" ]

env:
  REACT_APP_API_DOMAIN: ${{ secrets.REACT_APP_API_DOMAIN }}
  REACT_APP_AUTH_TOKEN_NAME: ${{ secrets.REACT_APP_AUTH_TOKEN_NAME }}
  REACT_APP_FB_ID: ${{ secrets.REACT_APP_FB_ID }}
  REACT_APP_GOOGLE_ID: ${{ secrets.REACT_APP_GOOGLE_ID }}
  REACT_APP_LOCATION: ${{ secrets.REACT_APP_LOCATION }}
  REACT_APP_AUTH_USER_INFO: ${{ secrets.REACT_APP_AUTH_USER_INFO }}

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: production
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm i --force

    - name: Build admin app
      run: npm run build:admin --if-present

    - name: Build Users App
      run: npm run build:app --if-present

    - name: 📂 Deploy Admin App
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: /packages/admin/build
        remote_path: /var/www/html/admin
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}

    - name: 📂 Deploy Users App
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: /packages/app/build
        remote_path: /var/www/html/app
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
