name: Deploy Frontend Apps

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Razón'
        required: true
        default: 'warning'
  push:
    branches: [ "main" ]

env:
  VITE_APP_API_DOMAIN: ${{ secrets.VITE_APP_API_DOMAIN }}
  VITE_APP_AUTH_TOKEN_NAME: ${{ secrets.VITE_APP_AUTH_TOKEN_NAME }}
  VITE_APP_FB_ID: ${{ secrets.VITE_APP_FB_ID }}
  VITE_APP_GOOGLE_ID: ${{ secrets.VITE_APP_GOOGLE_ID }}
  VITE_APP_LOCATION: ${{ secrets.VITE_APP_LOCATION }}
  VITE_APP_AUTH_USER_INFO: ${{ secrets.VITE_APP_AUTH_USER_INFO }}

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: production
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: pnpm-setup
      uses: pnpm/action-setup@v2
      with:
        version: 8.7.5

    - name: Install dependencies
      run: pnpm i --force

    - name: Build admin app
      run: pnpm run build:admin
      env:
        REACT_APP_NAME: 'admin'

    - name: Build Users App
      run: pnpm run build:web
      env:
        REACT_APP_NAME: 'web'

    - name: 📂 Deploy Admin frontend
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: /packages/admin/build
        remote_path: /var/www/html/admin
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}

    - name: 📂 Deploy Users web
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete
        path: /packages/web/build
        remote_path: /var/www/html/web
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_KEY }}
