name: Deploy Frontend Apps

on:
  push:
    branches: [ "main" ]

env:
    REACT_APP_API_DOMAIN: ${{ REACT_APP_API_DOMAIN }}
    REACT_APP_AUTH_TOKEN_NAME: ${{ REACT_APP_AUTH_TOKEN_NAME }}
    REACT_APP_FB_ID: ${{ REACT_APP_FB_ID }}
    REACT_APP_GOOGLE_ID: ${{ REACT_APP_GOOGLE_ID }}
    REACT_APP_LOCATION: ${{ REACT_APP_LOCATION }}
    REACT_APP_AUTH_USER_INFO: ${{ REACT_APP_AUTH_USER_INFO }}

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: production
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i --force
    - run: npm run build:admin --if-present
    - run: npm run build:app --if-present
